### ISSUE TITLE
弹幕全屏显示问题

### ISSUE THREAD

**Issue by Geekhyt** [aliyunvideo/AliyunPlayer_Web#104]
在播放器全屏状态下，弹幕并没有从最右边开始进入，从最左边开始离开。弹幕的活动区域是整个屏幕中间的一部分。请问这里应该如何配置？

**Comment by Geekhyt** [comment]
H5播放器模式下

**Comment by zhaoyingzi** [comment]
> H5播放器模式下



> 在播放器全屏状态下，弹幕并没有从最右边开始进入，从最左边开始离开。弹幕的活动区域是整个屏幕中间的一部分。请问这里应该如何配置？



> 在播放器全屏状态下，弹幕并没有从最右边开始进入，从最左边开始离开。弹幕的活动区域是整个屏幕中间的一部分。请问这里应该如何配置？

**Comment by Geekhyt** [comment]
？？

**Comment by zhaoyingzi** [comment]
> 在播放器全屏状态下，弹幕并没有从最右边开始进入，从最左边开始离开。弹幕的活动区域是整个屏幕中间的一部分。请问这里应该如何配置？

位置是CommentCoreLibrary.js这个插件封装好的，你可以看一下这个插件

**Comment by Geekhyt** [comment]
已解决，知道是这个插件，多谢。
