### ISSUE TITLE
Uncaught TypeError: t.getQuality is not a function

### ISSUE THREAD

**Issue by scriptpower** [aliyunvideo/AliyunPlayer_Web#108]
多清晰度URL切换里，报下述错误
`Uncaught TypeError: t.getQuality is not a function
    at HTMLUListElement.n.onclick (aliplayercomponents-1.0.5.min.js:20)
n.onclick @ aliplayercomponents-1.0.5.min.js:20
`
依赖文件版本：
https://g.alicdn.com/de/prismplayer/2.8.8/aliplayer-min.js
https://github.com/aliyunvideo/AliyunPlayer_Web/blob/master/customComponents/dist/aliplayer-components/aliplayercomponents-1.0.5.min.js

**Comment by scriptpower** [comment]
已找到原因，引用组件未传回调函数导致，指定args参数即可解决：
`
{
     name: "QualityComponent",
     type: AliPlayerComponent.QualityComponent,
      args:[(definition, desc) => {
          console.log({definition, desc})
     }]
}
`

**Comment by evestorm** [comment]
> 已找到原因，引用组件未传回调函数导致，指定args参数即可解决：
> 
> ```js
> {
>      name: "QualityComponent",
>      type: AliPlayerComponent.QualityComponent,
>       args:[(definition, desc) => {
>           console.log({definition, desc})
>      }]
> }
> ```

这种方案可行，不知道为啥官方例子没有把 args 写出来
