### ISSUE TITLE
Microsoft Edge浏览器无法播放rts直播

### ISSUE THREAD

**Issue by zhangliang2008** [aliyunvideo/AliyunPlayer_Web#151]
EDGE的chromium版本是89的,应该是支持的.
![alt 属性文本](https://gts-workorder.oss-cn-beijing.aliyuncs.com/20210306/fbf41689-54fa-48f0-bf71-b0ea3b92a578/QQ%E6%88%AA%E5%9B%BE20210306161242.png)
![alt 属性文本](https://gts-workorder.oss-cn-beijing.aliyuncs.com/20210306/680ef0d1-f014-4bfa-a635-f296c08c3b9a/QQ%E6%88%AA%E5%9B%BE20210306162900.png)
![alt 属性文本](https://gts-workorder.oss-cn-beijing.aliyuncs.com/20210306/5718db3d-d5bb-4418-bcd8-4deb1bd7e398/QQ%E5%9B%BE%E7%89%8720210306163247.png)

**Comment by zhaoyingzi** [comment]
> EDGE的chromium版本是89的,应该是支持的.
> ![alt 属性文本](https://camo.githubusercontent.com/55d5055d35a8f6871c033a15c862eb278cf6cb978dead8dd5e272dbd38df07cc/68747470733a2f2f6774732d776f726b6f726465722e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f32303231303330362f66626634313638392d353466612d343866302d626637312d6230656133623932613537382f515125453625383825414125453525394225424532303231303330363136313234322e706e67)
> ![alt 属性文本](https://camo.githubusercontent.com/6ce04674aa9f47a0e26ce4dd7aba26d6656eee188bf577f9b42e9bb12dc10d46/68747470733a2f2f6774732d776f726b6f726465722e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f32303231303330362f36383065663064312d663031342d346266612d613633352d6632393663303863336239612f515125453625383825414125453525394225424532303231303330363136323930302e706e67)
> ![alt 属性文本](https://camo.githubusercontent.com/0f0ece97a2f54b7fc577e6766dc9567a7e951e01f66c0674cff3e1885f388927/68747470733a2f2f6774732d776f726b6f726465722e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f32303231303330362f35373138646233642d643562622d343431382d626364382d3464656231626437653339382f515125453525394225424525453725383925383732303231303330363136333234372e706e67)

![image](https://user-images.githubusercontent.com/50280897/110726537-82e76a80-8254-11eb-9094-65dacabe049f.png)

**Comment by zhangliang2008** [comment]
我觉得是你们js检测问题, 新版edge用的是chromium版本是89的,本身是支持webrtc的

**Comment by zhaoyingzi** [comment]
> 我觉得是你们js检测问题, 新版edge用的是chromium版本是89的,本身是支持webrtc的

对，理论是是支持的，我这边加了isSupport的判断，你可以不加这个判断，直接让他播
