### ISSUE TITLE
请问错误代码4013代表什么？

### ISSUE THREAD

**Issue by baloyou** [aliyunvideo/AliyunPlayer_Web#19]
播放到一半，暂停再播放就会出现（m3u8）

**Comment by alilmq** [comment]
播放数据解码错误 MEDIA_ERR_DECODE，检测浏览器是否支持视频格式, 是不是那个切片有问题，浏览器解码不了

**Comment by baloyou** [comment]
> 播放数据解码错误 MEDIA_ERR_DECODE，检测浏览器是否支持视频格式, 是不是那个切片有问题，浏览器解码不了

我也怀疑是这个原因，不过是偶发情况，不知道是网络不稳定导致切片连不上了，还是其他的什么原因呢？
