### ISSUE TITLE
自定义组件问题

### ISSUE THREAD

**Issue by linghx** [aliyunvideo/AliyunPlayer_Web#2]
web端在使用flash播放器直播模式下发现以下问题：
1.发现引入 aliplayer-flash-min.js 时，是没有 Aliplayer.Component()方法的。
2.引入 aliplayer-min.js 时，自定义组件的生命周期节点没有触发
ps（引入的aliplayer版本都为2.6.0）

**Comment by alilmq** [comment]
1. flash不支持的
2. 有把组件给components属性赋值吗
