### ISSUE TITLE
怎么让  把设置里的菜单 显示在播放 按钮后面？

### ISSUE THREAD

**Issue by find456789** [aliyunvideo/AliyunPlayer_Web#22]
也就是让 设置 里的子菜单，和 播放按钮 同级别 ， 我复制到 children 下， 不显示呀

也不知道，设置里的菜单 的name 是什么，你们的文档 写得太差里

如果我用video.js   好像又无法和你们的 视频云 直接对接

`{
      "name": "controlBar",
      "align": "blabs",
      "x": 0,
      "y": 0,
      "children": [
        {
          "name": "progress",
          "align": "blabs",
          "x": 0,
          "y": 44
        },
        {
          "name": "playButton",
          "align": "tl",
          "x": 15,
          "y": 12
        },{
          "name": "speedButton",
          "align": "tl",
          "x": 15,
          "y": 12
        },{
          "name": "playButton",
          "align": "tl",
          "x": 15,
          "y": 12
        },
        {
          "name": "timeDisplay",
          "align": "tl",
          "x": 10,
          "y": 7
        },
        {
          "name": "fullScreenButton",
          "align": "tr",
          "x": 10,
          "y": 12
        },
        {
          "name": "setting",
          "align": "tr",
          "x": 15,
          "y": 12
        },
        {
          "name": "volume",
          "align": "tr",
          "x": 5,
          "y": 10
        }
      ]
    }`

**Comment by alilmq** [comment]
这个现在不支持的，还只能在设置里面，你是什么功能需要放到外面的
