### ISSUE TITLE
PlayAuth的播放方式下记忆播放的问题

### ISSUE THREAD

**Issue by nszbf** [aliyunvideo/AliyunPlayer_Web#23]
[#10](https://github.com/aliyunvideo/AliyunPlayer_Web/issues/10)
该问题依然存在，
我是用的PlayAuth的方式，打印出来player.getOptions().source.replace(/\?.*$/, '') 中参数Signature每一次都是变化的，所以还是失效了
![image](https://user-images.githubusercontent.com/16892834/50626660-72e3ea00-0f6a-11e9-8077-b1b6699411e3.png)

**Comment by alyzhao** [comment]
那你打印下 player.getOptions().source 的值看一下

**Comment by nszbf** [comment]
@alyzhao 好了，我问了官方，vid目前不支持记忆播放，我通过自定义组件解决了

**Comment by alyzhao** [comment]
@nszbf 主要我用我的 vid 和 playauth 播放是支持的, 正则是正确的。所以我想看看 你获得的 player.getOptions().source 是什么样的, 这样才能完善正则啊。

**Comment by alyzhao** [comment]
@nszbf 现在如果vid存在会根据vid去存储播放时间, 但是我用 vid 去播放的话, source 的 mp4 地址是一样的话是记忆记录是正确的, 看你打印出来的话 /?.*$/, 视频地址也是相同的, 除非 source 中有换行符, 正则匹配不到, **所以希望能贴出 player.getOptions().source **, 以便在不用 vid 播放的时候, source 记录播放时间更准确,

**Comment by nszbf** [comment]
@alyzhao  嗯 player.getOptions().source 就是我那个第一张图
![image](https://user-images.githubusercontent.com/16892834/51010065-97088200-158d-11e9-9354-3047de5ba061.png)

**Comment by alyzhao** [comment]
@nszbf 可以复制两个, 完整的地址么?我测试一下

**Comment by nszbf** [comment]
@alyzhao  
https://outin-7dd6c2dd04bc11e9827300163e1c91c8.oss-cn-shanghai.aliyuncs.com/d095c658fc4e4333b9eed4d41259bd53/8a5cb48d0ba545b4861a405fa1484330-dc3dc8639d4721ef909a91ab2c3d9c0a-ld.mp4?Expires=1547183141&OSSAccessKeyId=LTAIx2xjxmIyFov4&Signature=sgkGoL4ucmpCfiTF5KnED77Rhhg%3D

https://outin-7dd6c2dd04bc11e9827300163e1c91c8.oss-cn-shanghai.aliyuncs.com/0dcd6977f51f4477a07c683692067225/f9437e7232814958acce0f3bca534ad5-4e00ff69f2c7fca7952546e6bc23d125-ld.mp4?Expires=1547183483&OSSAccessKeyId=LTAIx2xjxmIyFov4&Signature=SsO2OQUb7aIqsZojmLa5%2F7fBdp0%3D

**Comment by alyzhao** [comment]
@nszbf 测了下这两个地址都是能按照 xxx.mp4 去存储 localStorage 的, 我这边是好的啊。你是拷贝的代码直接用的还是, 用那个在线的播放器组件地址的？

**Comment by nszbf** [comment]
@alyzhao  ...额，确实按这样是好了的正则也就是这样，我看以前提交记录文件这块好像也没变过=。=，我的过错。
具体上一次为什么会错我也忘了额(上面我发的图也确实是localStorage里面存储的)..很奇怪，哈哈^_^

**Comment by alyzhao** [comment]
@nszbf 引用线上的 https://player.alicdn.com/aliplayer/presentation/js/aliplayercomponents.min.js 这个地址的话, 这个地址导报后的js还没更新, 是会失效的。这个在线的js会和播放器的sdk一起更新的。

**Comment by nszbf** [comment]
@alyzhao   嗯 好的Thanks♪(･ω･)ﾉ

**Comment by nszbf** [comment]
@alyzhao   大哥 你只改了getItem 没有改 setItem 额...导致一直使用source存的 但是去却是用的vid

**Comment by nszbf** [comment]
![image](https://user-images.githubusercontent.com/16892834/51174144-14b3f100-18f2-11e9-8cc0-40c11e9c12ce.png)
![image](https://user-images.githubusercontent.com/16892834/51174184-2ac1b180-18f2-11e9-8018-6cedeaa778ea.png)
![image](https://user-images.githubusercontent.com/16892834/51174232-49c04380-18f2-11e9-8a96-4810abba6f03.png)

很奇怪，我不知道为什么存在localstorage里面的还是原本的source，但是正则完确实是去掉了？后的值

**Comment by nszbf** [comment]
@alyzhao  [aliplayercomponents.min.js](http://player.alicdn.com/aliplayer/presentation/js/aliplayercomponents.min.js)

![image](https://user-images.githubusercontent.com/16892834/51174804-a8d28800-18f3-11e9-966b-5392c837ca15.png)


![image](https://user-images.githubusercontent.com/16892834/51174790-9f492000-18f3-11e9-97f1-427759f077f0.png)

源码里面没有改..

**Comment by alyzhao** [comment]
setMemory 里面确实是忘了调换 vid 和 source 的 顺序了, 一开始没有考虑到参数, source.replace(/\?.*$/, '') 但是这个正则我暂时还没测试到去不掉参数的情况, 你这个打包出来的代码是引用官网在线的？这个打包的更新不及时, 建议直接使用源码, github 仓库里的代码。 @nszbf

**Comment by alyzhao** [comment]
现在已经在着手弄一个专门的组件仓库, 目前这些组件还没有发布npm仓库只是把源码放在这儿, https://github.com/aliyunvideo/AliyunPlayer_Web/tree/master/customComponents/src/components/MemoryPlayComponent 这个目录下的文件你可以复制到项目中, 引用 import memoryComponent from  'MemoryPlayComponent/index.js' 就能在播放器中使用这个组件了。

**Comment by nszbf** [comment]
@alyzhao  嗯 好的Thanks♪(･ω･)ﾉ
