### ISSUE TITLE
热启动和线上版本点击播放器按钮报错，请问怎么解决？

### ISSUE THREAD

**Issue by lkjtzsq** [aliyunvideo/AliyunPlayer_Web#24]
![qq 20190107112613](https://user-images.githubusercontent.com/32919242/50747557-6bc12280-126f-11e9-90af-322205271cf8.png)

**Comment by lkjtzsq** [comment]
抱歉，问题描述的不准确，不是点击播放器按钮，应该是点击播放器视频播放区域的时候会报这个错误，
http://player.alicdn.com/demo/h5live/index.html
http://player.alicdn.com/demo/h5/index.html 
你们线上这两个demo都会报错

**Comment by alilmq** [comment]
可以看一下那个地方用调用zepto里的方法抛错误
