### ISSUE TITLE
直播没有暂停组件

### ISSUE THREAD

**Issue by liziwl** [aliyunvideo/AliyunPlayer_Web#254]
直播没有暂停太奇怪了，只有个live在左下方。

期望这个样子
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/23000702/160279720-c0670dc0-5d61-416b-9101-a06b0950f6ea.png">

但是现在只有这个样子，live在左下角不能暂停。
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/23000702/160279737-a5d90d39-1e0f-4e9c-8edd-4017a1ba3b29.png">

**Comment by zhaoyingzi** [comment]
是的，播放器在直播模式下没有暂停按钮。
