### ISSUE TITLE
vid+playauth实现试看功能，过了试看时间后如何让视频继续播放下去

### ISSUE THREAD

**Issue by lukerlv** [aliyunvideo/AliyunPlayer_Web#261]
你好，请问一下，vid+playauth实现试看功能，过了试看时间后如何让视频继续播放下去。player.setPreviewTime(0)之后没有效果。

**Comment by lukerlv** [comment]
@zhaoyingzi https://player.alicdn.com/aliplayer/presentation/index.html?type=preview 是这个例子的试看，vid+playauth方式

**Comment by zhaoyingzi** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我将尽快给您回复。
