### ISSUE TITLE
使用视频开始广告startAd，在倒计时没有结束时，切换其他路由报错Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by NaroXing** [aliyunvideo/AliyunPlayer_Web#266]
在视频开始广告没有结束之前，切换其他路由报错

Cannot read properties of null (reading 'removeChild')   
 key: "removeComponent", value: function () {
      this.html.parentNode.removeChild(this.html), this.html = null
   }
   因为在定时器还没关闭 其父容器播放器盒子被销毁 报错 自己能力有限没有改成功  求大佬解答 有点急 希望看到帮忙看一下谢谢

**Comment by NaroXing** [comment]
![error](https://user-images.githubusercontent.com/111257755/184563821-edeecb48-563a-4f72-a18f-f360be4e2d4a.png)

**Comment by raxxarr** [comment]
你好，这确认是组件内部的 bug，需要在销毁播放器时清空组件内部所有的定时器和状态。如果你方便可以自己修改源代码并构建，如果想快速解决问题，可以尝试在离开路由之前先 mock 一些数据结构让定时器回调不报错：

```
  function clear() {
    // 获取组件
    var comp = player.getComponent('StartADComponent');
    // 构造一些数据给未来定时器调用
    comp.html = { parentNode: {
      removeChild: () => {} // noop
    } }
    // 销毁播放器
    player.dispose();
    // 构造一些数据给未来定时器调用
    player.getOptions = () => ({ vid: 'x', components: [] });
    player = null;
  }
```

**Comment by NaroXing** [comment]
感谢您的解答，我是一个小白，您的这段代码如果 直接放在 aliplayercomponents-1.0.8.min.js 中可以解决问题吗

**Comment by NaroXing** [comment]
感谢您的回答，我是一个小白，您的特定代码如果直接在 aliplayercomponents-1.0.8.min.js 中可以解决问题吗

**Comment by NaroXing** [comment]
非常感谢您的帮助
