### ISSUE TITLE
同是 mp4 视频 ，在安卓手机 上 有的出现 下载按钮，有的不出现下载按钮？

### ISSUE THREAD

**Issue by JoMartinezZhu** [aliyunvideo/AliyunPlayer_Web#27]
同是 mp4 视频 ，在安卓手机 上 有的出现 下载按钮，有的不出现下载按钮？

**Comment by alilmq** [comment]
这个应该是浏览器的行为， 视频播放被浏览器劫持，使用浏览器自动的播放器会出现下载按钮，一般自带浏览器，QQ浏览器会劫持， Chrome, firefox就不会劫持

**Comment by JoMartinezZhu** [comment]
> 这个应该是浏览器的行为， 视频播放被浏览器劫持，使用浏览器自动的播放器会出现下载按钮，一般自带浏览器，QQ浏览器会劫持， Chrome, firefox就不会劫持

针对这个 防止移动浏览器下载 问题，有什么 解决思路嘛？

**Comment by alilmq** [comment]
如是HLS，可以使用阿里云点播服务的标准加密
