### ISSUE TITLE
跑马灯组件位置

### ISSUE THREAD

**Issue by chowyu08** [aliyunvideo/AliyunPlayer_Web#28]
如果设置跑马灯组件的位置相对播放器视频范围内显示？

**Comment by alyzhao** [comment]
@chowyu08 你是说在水平范围内显示么？可以重写`.bullet-screen`的animation属性, 自定义一个动画, `@keyframes bullet {
  from {
    left: 100%;
  }
  to {
    left: 0;
    transform: translateX(-100%) 
  }
}`
原来的动画是这个, 可以参考这个。
