### ISSUE TITLE
打包自定义组件时报错：'.' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by mu-orange** [aliyunvideo/AliyunPlayer_Web#283]
![image](https://user-images.githubusercontent.com/57793402/198270511-28a2862c-99e8-4c65-88fa-b5d02a92e96a.png)

**Comment by zhaoyingzi** [comment]
> ![image](https://user-images.githubusercontent.com/57793402/198270511-28a2862c-99e8-4c65-88fa-b5d02a92e96a.png)
执行 npm run build Rate即可，不需要添加Component
![image](https://user-images.githubusercontent.com/50280897/199166307-a166ff2d-4d36-4e27-9c10-06a12f81c993.png)

**Comment by mu-orange** [comment]
> > ![image](https://user-images.githubusercontent.com/57793402/198270511-28a2862c-99e8-4c65-88fa-b5d02a92e96a.png)
> > 执行 npm run build Rate即可，不需要添加Component
> > ![image](https://user-images.githubusercontent.com/50280897/199166307-a166ff2d-4d36-4e27-9c10-06a12f81c993.png)
执行 npm run build Rate报同样的错，执行npm run build也是一样

**Comment by zhaoyingzi** [comment]
检查一下环境，可能是环境问题引起的编译失败，看看node是什么版本的，命令没有问题
![image](https://user-images.githubusercontent.com/50280897/199170400-5ef6be15-730d-4be6-8ae9-89940a8e94d9.png)

**Comment by mu-orange** [comment]
终于搞定，记录一下

1. git clone后执行npm i命令安装依赖，报错信息如下：
![image](https://user-images.githubusercontent.com/57793402/199421283-0931b18a-11b6-4c15-9daf-af479901a88e.png)

这是由于node-sass不兼容当前node版本的提示信息，我的node版本是16,降到14后完美解决

2.执行npm run build命令报错“'.' 不是内部或外部命令，也不是可运行的程序”，需要在package.json中将build执行命令修改为".\\build_customize.sh"，因为Win10系统是将"." 当成要执行的命令了，所以要转义一下。windows环境下build_customize按文档配置
![image](https://user-images.githubusercontent.com/57793402/199419324-2b5a0d66-b69c-43bc-b12c-028261180951.png)

3. 以上两步完成后执行“npm run build 组件名称”  命令即可打包生成自定义组件的js文件

**Comment by zhaoyingzi** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我将尽快给您回复。
