### ISSUE TITLE
Vuedemo下载下来没有办法运行

### ISSUE THREAD

**Issue by HTingting** [aliyunvideo/AliyunPlayer_Web#29]
![image](https://user-images.githubusercontent.com/30112097/55284228-bd77d580-53a4-11e9-8958-1bce5165daf4.png)
![image](https://user-images.githubusercontent.com/30112097/55284229-c668a700-53a4-11e9-880a-eca0b398f254.png)

**Comment by alyzhao** [comment]
@HTingting Windows系统下, 要将 package.json 的 dev 命令改为, `set NODE_ENV=development&&webpack-dev-server --inline --hot --host 0.0.0.0`, Windows和unix系统申明系统变量的方式不一样。

**Comment by alyzhao** [comment]
现在更新了代码, 重新拉取代码 H5VodVueDemo, Windows系统下, 开发使用`npm run dev_win`, 打包使用`npm run build_win`

**Comment by gfdfgd2016** [comment]
22 error aliplayerdemo@1.0.0 dev_win: `set NODE_ENV=development&&webpack-dev-server --inline --hot --host 0.0.0.0`  无法运行
