### ISSUE TITLE
多路视频同时播放频繁刷新，导致视频延迟

### ISSUE THREAD

**Issue by Lecrazy** [aliyunvideo/AliyunPlayer_Web#31]
你好，在aliplayer-web（2.7.4版本）使用过程中，发现一个现象。同时播放多路视频（4路或9路），出现视频频繁刷新问题（视频播放窗口转圈），最终导致视频延迟。

**Comment by alilmq** [comment]
可以使用最新版本看看， 是直播视频？频繁刷新是缓存不足，或者播放失败重新重试
