### ISSUE TITLE
关于字幕外挂

### ISSUE THREAD

**Issue by HTingting** [aliyunvideo/AliyunPlayer_Web#32]
请问，有没有相关接口可以提供，可以自定义字幕文件实现自定义字幕
![image](https://user-images.githubusercontent.com/30112097/56274076-a2d98680-6130-11e9-8a38-0794ff2e2e83.png)
如果是这样的话，字幕这就不算一个功能了吧？o(╯□╰)o

**Comment by alilmq** [comment]
字幕文件需要自己准备，通过转码服务打包hls时，可以把字幕文件打包进去，参考文档： https://help.aliyun.com/document_detail/68617.html?spm=a2c4g.11186623.6.599.6ef840d6w6v8xp
