### ISSUE TITLE
刷新页面，视频不能自动播放

### ISSUE THREAD

**Issue by wtmjldev** [aliyunvideo/AliyunPlayer_Web#35]
启动项目，进入页面当前的视频不能播放，刷新页面也不能播放。
点击右侧的其他视频可以播放。

**Comment by wtmjldev** [comment]
有没有解决办法

**Comment by alyzhao** [comment]
@wtmjldev  哪个项目的？

**Comment by wtmjldev** [comment]
AliyunPlayer_Web/H5VodVueDemo

**Comment by alyzhao** [comment]
![image](https://user-images.githubusercontent.com/24472439/56859684-f4033900-69c0-11e9-9fa8-71b0e12e34aa.png)

**Comment by wtmjldev** [comment]
感谢

**Comment by alyzhao** [comment]
you're welcome
