### ISSUE TITLE
跑马灯组件的透明度无法设置为小数

### ISSUE THREAD

**Issue by BerkerDong** [aliyunvideo/AliyunPlayer_Web#36]
opacity 参数无法设置为 小数，比如 0.3，现在如果设置为 小数会被自动刷新为 1，如果 为 1的话，字体不够透明，希望可以调整

**Comment by alyzhao** [comment]
**设置跑马等的 style 时, display, opacity, visibility 不能设置, 这是为了防止被删除, 隐藏。**你可以设置 `color: 'rgba(0, 193, 222, .3)'` 改变字体颜色的透明度。
