### ISSUE TITLE
安卓微信播放，上下有黑边。

### ISSUE THREAD

**Issue by loveksmy** [aliyunvideo/AliyunPlayer_Web#39]
安卓微信播放，上下有黑边。
![image](https://user-images.githubusercontent.com/41360355/58537869-69636300-8226-11e9-8e8f-ece4e69b9e05.png)
现在是左边图效果，想要达到右边图效果。

**Comment by alilmq** [comment]
通过video的object-fit属性，设置一下

**Comment by loveksmy** [comment]
不知道安卓微信X5浏览器是不是更新了，现在不用同层也能实现不全屏播放和自定义控制栏这些了。多谢回复。
