### ISSUE TITLE
Mobile progress bar broadcast control problem

### ISSUE THREAD

**Issue by CheetoCheeto** [aliyunvideo/AliyunPlayer_Web#41]
If the video broadcast control area is left blank, slides the progress bar to the left side of the starting point, and the progress bar will go to the right side。
——————————————————————————
如果移动端视频区域左右留白的话，滑动进度条至左侧空白区而进度条会向右边走。当前版本demo在chrome下使用手机模拟器可以复现这个问题。

**Comment by alilmq** [comment]
在容器里留白，还是外面留白？ 可以尝试在外面留白

**Comment by CheetoCheeto** [comment]
> 在容器里留白，还是外面留白？ 可以尝试在外面留白

感谢您的回复。因为UI要求的关系，是在容器里留白。
