### ISSUE TITLE
Android手机端 在支付宝、钉钉中打开视频，使用seek函数，不会跳过相应秒数。

### ISSUE THREAD

**Issue by qinqiuqiu** [aliyunvideo/AliyunPlayer_Web#45]
Android 手机 小米min2 ，播放器js: aliplayer-min-2.8.2.js  钉钉 ：v4.6.33  支付宝：10.1.65
 var player = new Aliplayer({
				id: 'J_prismPlayer',
				width: '100%',
				autoplay: false,
				//支持播放地址播放,此播放优先级最高
				source : '720/720_md5_.m3u8'            
				},function(player){
					console.log('播放器创建好了。')
			    }
			);
 player.on("loadedmetadata",function(){ 
	player.seek(25); 
 }); 通过记录播放时长，跳过指定秒数； 在Chrome、Android端 微信测试可以正常跳播

**Comment by alilmq** [comment]
钉钉会劫持播放器，使用自带的播放， 行为会不一样， 可以订阅canplay事件试一下，另外canplay事件会触发多次，需要加一个判断
