### ISSUE TITLE
m3u8视频地址不能正常播放，只能播放明确文件类型的视频

### ISSUE THREAD

**Issue by hiqiyanan** [aliyunvideo/AliyunPlayer_Web#46]
m3u8视频地址没有后缀名 ‘.m3u8’ ，aliplayer不能正常播放，显示4400 播放失败，只能播放明确是m3u8类型视频链接。
比如 `http://www.sdas.xxxx/sdf.mp4` 或者 `http://www.sdas.xxxx/ssd.m3u8` 可以正常播放，
但  `http://www.sdas.xxxx/sdf`  （视频源是m3u8）的就报错4400 播放失败。

**Comment by hiqiyanan** [comment]
希望可以解决一下，谢谢

**Comment by alilmq** [comment]
是的，现在需要带m3u8， 在设置跳转地址的时候，可以加一个后坠，有的浏览器不支持m3u8，需要提前判断加载插件，才可以播放

**Comment by hiqiyanan** [comment]
好的，谢谢
