### ISSUE TITLE
npm run pc 报错

### ISSUE THREAD

**Issue by DreamToKing** [aliyunvideo/AliyunPlayer_Web#48]
webpack-dev-server --devtool eval --config webpack.pc.config.js --progress --hot --content-base
提示这个错误，pc和mobile这个版本npm run 报错

**Comment by DreamToKing** [comment]
Cannot find module 'webpack-cli/bin/config-yargs'

**Comment by alyzhao** [comment]
试着把 nodel_modules 删掉, 重新 npm install 试试
