### ISSUE TITLE
官方文档命名和解释的理解问题

### ISSUE THREAD

**Issue by longting** [aliyunvideo/AliyunPlayer_Web#56]
x5开头的属性有什么其他的含义 ？ 这些属性命名怎么跟腾讯X5浏览器的名字一样 ? 
![image](https://user-images.githubusercontent.com/5129611/64399395-e199ba00-d09a-11e9-99f9-dc8354b87e88.png)

**Comment by alilmq** [comment]
在微信上时，会映射到X5对应的属性
