### ISSUE TITLE
请问播放器请求阿里巴巴公司的track接口是怎么回事？

### ISSUE THREAD

**Issue by longting** [aliyunvideo/AliyunPlayer_Web#57]
![image](https://user-images.githubusercontent.com/5129611/64399847-8ec10200-d09c-11e9-8a48-2ab18224cb24.png)

**Comment by alilmq** [comment]
这个是记录使用情况方便排查问题

**Comment by cooper1x** [comment]
@alilmq 这个怎么关掉呢，内网视频播放，报错太多了。
