### ISSUE TITLE
直播有的时候会播放不了 

### ISSUE THREAD

**Issue by samblabla** [aliyunvideo/AliyunPlayer_Web#58]
点击会报错 aliplayer-min.js:2 Uncaught ReferenceError: liveForceLoad is not defined
![WX20190906-180154](https://user-images.githubusercontent.com/3224632/64419992-b5992b80-d0d0-11e9-87e8-8779fced62e6.png)

**Comment by alilmq** [comment]
这个新版本会修改掉

**Comment by fengyingdian** [comment]
还没修复
