### ISSUE TITLE
文档关闭状态持续了一周，打算什么时候开放？有没有考虑把文档放一份到github

### ISSUE THREAD

**Issue by longting** [aliyunvideo/AliyunPlayer_Web#61]
![image](https://user-images.githubusercontent.com/5129611/65661358-0662cb00-e064-11e9-87c6-97ae1f3ac502.png)

**Comment by alilmq** [comment]
现在的文档地址是： https://help.aliyun.com/document_detail/125570.html
可以清一下缓存
