### ISSUE TITLE
您好支持断点续播吗 webpack4.x的话要改哪些配置项昵

### ISSUE THREAD

**Issue by qappleh** [aliyunvideo/AliyunPlayer_Web#7]
您好支持断点续播吗 webpack4.x的话要改哪些配置项昵

**Comment by alilmq** [comment]
已经有记忆播放的插件组件了https://github.com/aliyunvideo/AliyunPlayer_Web/tree/master/customComponents

演示地址：https://player.alicdn.com/aliplayer/presentation/index.html
