### ISSUE TITLE
2.8.2版本flash播放器的几个问题

### ISSUE THREAD

**Issue by chillyond** [aliyunvideo/AliyunPlayer_Web#72]
使用的资源版本：`https://g.alicdn.com/de/prismplayer/2.8.2/aliplayer-flash-min.js`
以下是一个基本的配置：
``` js
const player = new Aliplayer({
          id: 'container',
          source: 'http://localhost:8000/live/landscape.flv',
          autoplay: true,
          width: '100%',
          height: '100%',
          isLive: true
})
player.on('ready', event => {
          player.setVolume(1)
})
```
问题一：不能在初始化的时候设置默认音量，`ready`事件中立刻设置会出现一个Toast;
问题二：控制条右侧的按钮出现重叠，左侧没有播放按钮也没有`LIVE`字样，https://help.aliyun.com/document_detail/62948.html?spm=a2c4g.11186623.2.21.IHJU9w&accounttraceid=cecf6fad56e640a5994c9e445d1d4029hmtq 通过此文档提到的默认skinLayout设置亦不能达到文档中给的图片效果。
![image](https://user-images.githubusercontent.com/11400674/69615467-e190d100-106f-11ea-8925-2410e466e294.png)

**Comment by chillyond** [comment]
使用falsh版本的时候，在`ready`事件里设置静音不生效：
``` js
const player = ...
 player.on('ready', function(e) {
    player.setVolume(0); // 0会变成50%，其它非0才能正常设置成功
 });
```

**Comment by yz666888** [comment]
在vue项目中使用播放器自定义组件出现如下错误:
error  in ./src/components/PauseADComponent/index.html

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <div class="pause-ad">
|   <a class="btn-close">
|     <i class="split-left"></i>

**Comment by yanjieyv** [comment]
flash 控制条 live 文字 需要设置liveDisplay

**Comment by yanjieyv** [comment]
flash全屏有时会在底部留下一大截黑色区域,不能铺满屏幕.

**Comment by zhaoyingzi** [comment]
> 使用falsh版本的时候，在`ready`事件里设置静音不生效：
> 
> ```js
> const player = ...
>  player.on('ready', function(e) {
>     player.setVolume(0); // 0会变成50%，其它非0才能正常设置成功
>  });
> ```
