### ISSUE TITLE
本地使用播放器组件js后报错

### ISSUE THREAD

**Issue by Roned** [aliyunvideo/AliyunPlayer_Web#77]
aliplayercomponents-1.0.5.min.js:20 Uncaught TypeError: t.getQuality is not a function，清晰度组件，线上示例没有这种情况。

**Comment by chua1989** [comment]
本人也是这种情况。源代码中需要传递一个getQuality方法初始化，但是例子中没有啊
![image](https://user-images.githubusercontent.com/17613057/71810295-00da3f80-30ad-11ea-986b-aea328e4e3cc.png)

**Comment by Roned** [comment]
已解决，需要自定义参数
          var getQuality = function () {}    
           components = [
              {
                name: "QualityComponent",
                type: AliPlayerComponent.QualityComponent,
                args: [getQuality]
              }]

**Comment by chua1989** [comment]
感觉不应该就这么关掉，做一下容错 @Roned
