### ISSUE TITLE
使用demo flash版可以播，h5版不能播

### ISSUE THREAD

**Issue by fancyboynet** [aliyunvideo/AliyunPlayer_Web#8]
测试流地址：http://s3.cn-north-1.amazonaws.com.cn/wlmedia/qa/test/h5test3.m3u8

**Comment by alilmq** [comment]
[NULL @ 0x7fe1af827400] non-existing PPS 0 referenced
[h264 @ 0x7fe1af828c00] non-existing PPS 0 referenced
[h264 @ 0x7fe1af828c00] decode_slice_header error
[h264 @ 0x7fe1af828c00] no frame!
https://stackoverflow.com/questions/15005436/errors-when-decode-h-264-frames-using-ffmpeg

**Comment by fancyboynet** [comment]
@alilmq 第一帧没有关键帧，后面帧是正常的，可以像flash一样把后面的也播放出来吗

**Comment by alilmq** [comment]
这个支持应该没这么快，你们可以先处理一下视频先

**Comment by fancyboynet** [comment]
好的，感谢回答
