### ISSUE TITLE
H5点播只能播放mp4吗？m3u8怎么播放呢

### ISSUE THREAD

**Issue by Tweicx** [aliyunvideo/AliyunPlayer_Web#9]
m3u8类型的视频h5用playauth方式提示加密视频h5无法播放，有什么办法吗

**Comment by alilmq** [comment]
现在h5只能播放hls的标准加密，https://help.aliyun.com/document_detail/68612.html?spm=5176.10695662.1996646101.searchclickresult.61e9cfcdj1MYL8

**Comment by Tweicx** [comment]
好的  谢谢
