### ISSUE TITLE
进度条问题

### ISSUE THREAD

**Issue by Banlangenn** [aliyunvideo/AliyunPlayer_Web#92]
监听 ‘ended’ 用 loadByUrl 下一个视频
这个时候如果把进度条拖到底 - 进入下一个视频 =会出现直接在末尾播放

**Comment by zhaoyingzi** [comment]
> 监听 ‘ended’ 用 loadByUrl 下一个视频
> 这个时候如果把进度条拖到底 - 进入下一个视频 =会出现直接在末尾播放

请问您用的是什么版本的sdk呢？
这个是毕现的吗？

**Comment by Banlangenn** [comment]
自己的问题
